name: Code Test

on:
  push:
    branches:
      - main

jobs:
  check-comments:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: node test.js
